version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Password!
      - DOCKER_INFLUXDB_INIT_ORG=apm-org
      - DOCKER_INFLUXDB_INIT_BUCKET=apm-bucket
    volumes:
      - /data:/var/lib/influxdb2