server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: Password!
    url: jdbc:mysql://localhost:3306/terra
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug